### ISSUE TITLE
configure: error: GStreamer 1.0 required

### ISSUE THREAD

**Issue by thorus90** [thaytan/aurena#13]
Hi,

I want to test aurena on my raspberry pi, but while executing ./configure I get the error:

configure: Checking for GStreamer 1.0
checking for GST_1_0... no
configure: error: GStreamer 1.0 required

Can you tell me what package I require to fulfill this requirement, as I can't figure it out on my own...

I already installed gstreamer1.0* , but this didn't do the trick.

Thanks

**Comment by thaytan** [comment]
I think libgstreamer1.0-dev and libgstreamer-plugins-base1.0-dev should do it.

**Comment by thorus90** [comment]
thanks, I was missing libgstreamer-plugins-base1.0-dev.
