### ISSUE TITLE
no src/aurena executable after make

### ISSUE THREAD

**Issue by thorus90** [thaytan/aurena#14]
I was now able to compile aurena, but there is no src/aurena executable as mentioned in readme?. perhaps I need some ./configure options?

thanks again

**Comment by thaytan** [comment]
Sorry - executable names changed since I first wrote the README

**Comment by thorus90** [comment]
i hate to say, but I also don't have an src/aurena-server
these are the only executables in src I have:

aurena-simple-client
gnome-client.py

**Comment by thaytan** [comment]
Check the output that configure is printing - building the server requires sqlite (>= v3.3) and newer glib (>=2.32) and libsoup (>2.48) than the client. I'll add a note about that to the README too.
